In [1]:
import os

import pandas as pd 
import numpy as np
import datetime

  # can directly import from the folder by defining the folder name

In [2]:
os.chdir(r"D:\1.Work\WorkStation\WorkSpace\Projects\Dynamic-Portfolio-Allocation")
path = os.getcwd()

from data.metadata import features, stocks
from src.ingest import update_ticker

In [ ]:
datetime.date.today()

2026-04-11

In [11]:
'''
for i in features:
    update_ticker(i,path)

for i in stocks:
    update_ticker(i,path)
'''

'\nfor i in features:\n    update_ticker(i,path)\n\nfor i in stocks:\n    update_ticker(i,path)\n'

In [25]:
df = pd.DataFrame()

for i in features:
    if df.empty:
        df = pd.read_csv(os.path.join(path,'data','processed',f'p-{i}.csv'),index_col=0)
        df.set_index('Date',inplace=True)
    else:
        right = pd.read_csv(os.path.join(path,'data','processed',f'p-{i}.csv'),index_col=0)
        right.set_index('Date',inplace=True)
    
        df = pd.concat([df,right],join='inner',axis=1)
        
df.to_csv(os.path.join(path,'data','final','Dataset.csv'))

In [23]:
df

,GSPC-Close,GSPC-Dividends,GSPC-High,GSPC-Low,GSPC-Open,GSPC-Stock Splits,GSPC-Volume,SS-Close,SS-Dividends,SS-High,...,HG-Open,HG-Stock Splits,HG-Volume,VIX-Close,VIX-Dividends,VIX-High,VIX-Low,VIX-Open,VIX-Stock Splits,VIX-Volume
Date,,,,,,,,,,,,,,,,,,,,,
2015-11-18,2083.580078,0.0,2085.310059,2051.989990,2051.989990,0.0,3926390000,3568.468018,0.0,3617.069092,...,2.0885,0.0,277,16.850000,0.0,19.450001,16.799999,19.010000,0.0,0
2015-11-19,2081.239990,0.0,2086.739990,2078.760010,2083.699951,0.0,3628110000,3617.062012,0.0,3618.212891,...,2.0795,0.0,296,16.990000,0.0,18.260000,16.000000,16.250000,0.0,0
2015-11-20,2089.169922,0.0,2097.060059,2082.820068,2082.820068,0.0,3929600000,3630.500000,0.0,3640.529053,...,2.0945,0.0,270,15.470000,0.0,16.379999,15.470000,16.129999,0.0,0
2015-11-24,2089.139893,0.0,2094.120117,2070.290039,2084.419922,0.0,3884930000,3616.113037,0.0,3616.483887,...,2.0230,0.0,361,15.930000,0.0,17.209999,15.480000,16.530001,0.0,0
2015-11-27,2090.110107,0.0,2093.290039,2084.129883,2088.820068,0.0,1466840000,3436.302979,0.0,3621.896973,...,2.0440,0.0,20906,15.120000,0.0,16.090000,15.120000,15.310000,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-11,6846.609863,0.0,6855.129883,6806.870117,6815.640137,0.0,4983490000,4002.758057,0.0,4024.938965,...,5.0425,0.0,685,17.280001,0.0,18.010000,17.250000,17.900000,0.0,0
2025-11-12,6850.919922,0.0,6869.910156,6829.620117,6867.770020,0.0,5293610000,4000.139893,0.0,4020.376953,...,5.0430,0.0,656,17.510000,0.0,18.059999,17.100000,17.209999,0.0,0
2025-11-13,6737.490234,0.0,6828.049805,6724.720215,6826.470215,0.0,5473720000,4029.500977,0.0,4030.397949,...,5.0995,0.0,795,20.000000,0.0,21.309999,17.510000,17.610001,0.0,0
2025-11-14,6734.109863,0.0,6774.310059,6646.870117,6672.140137,0.0,5042660000,3990.491943,0.0,4034.079102,...,5.0510,0.0,780,19.830000,0.0,23.030001,19.559999,21.330000,0.0,0
2025-11-17,6672.410156,0.0,6754.500000,6638.899902,6713.609863,0.0,5204220000,3972.034912,0.0,3992.404053,...,4.9980,0.0,780,22.379999,0.0,23.440001,19.540001,19.580000,0.0,0

In [26]:
pd.read_csv(os.path.join(path,'data','final','Dataset.csv'))

,Date,GSPC-Close,GSPC-Dividends,GSPC-High,GSPC-Low,GSPC-Open,GSPC-Stock Splits,GSPC-Volume,SS-Close,SS-Dividends,...,HG-Open,HG-Stock Splits,HG-Volume,VIX-Close,VIX-Dividends,VIX-High,VIX-Low,VIX-Open,VIX-Stock Splits,VIX-Volume
0,2015-11-18,2083.580078,0.0,2085.310059,2051.989990,2051.989990,0.0,3926390000,3568.468018,0.0,...,2.0885,0.0,277,16.850000,0.0,19.450001,16.799999,19.010000,0.0,0
1,2015-11-19,2081.239990,0.0,2086.739990,2078.760010,2083.699951,0.0,3628110000,3617.062012,0.0,...,2.0795,0.0,296,16.990000,0.0,18.260000,16.000000,16.250000,0.0,0
2,2015-11-20,2089.169922,0.0,2097.060059,2082.820068,2082.820068,0.0,3929600000,3630.500000,0.0,...,2.0945,0.0,270,15.470000,0.0,16.379999,15.470000,16.129999,0.0,0
3,2015-11-24,2089.139893,0.0,2094.120117,2070.290039,2084.419922,0.0,3884930000,3616.113037,0.0,...,2.0230,0.0,361,15.930000,0.0,17.209999,15.480000,16.530001,0.0,0
4,2015-11-27,2090.110107,0.0,2093.290039,2084.129883,2088.820068,0.0,1466840000,3436.302979,0.0,...,2.0440,0.0,20906,15.120000,0.0,16.090000,15.120000,15.310000,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2069,2025-11-11,6846.609863,0.0,6855.129883,6806.870117,6815.640137,0.0,4983490000,4002.758057,0.0,...,5.0425,0.0,685,17.280001,0.0,18.010000,17.250000,17.900000,0.0,0
2070,2025-11-12,6850.919922,0.0,6869.910156,6829.620117,6867.770020,0.0,5293610000,4000.139893,0.0,...,5.0430,0.0,656,17.510000,0.0,18.059999,17.100000,17.209999,0.0,0
2071,2025-11-13,6737.490234,0.0,6828.049805,6724.720215,6826.470215,0.0,5473720000,4029.500977,0.0,...,5.0995,0.0,795,20.000000,0.0,21.309999,17.510000,17.610001,0.0,0
2072,2025-11-14,6734.109863,0.0,6774.310059,6646.870117,6672.140137,0.0,5042660000,3990.491943,0.0,...,5.0510,0.0,780,19.830000,0.0,23.030001,19.559999,21.330000,0.0,0
2073,2025-11-17,6672.410156,0.0,6754.500000,6638.899902,6713.609863,0.0,5204220000,3972.034912,0.0,...,4.9980,0.0,780,22.379999,0.0,23.440001,19.540001,19.580000,0.0,0

In [43]:
nvidia = pd.read_csv(os.path.join(path,'data','raw',f'{itemset.stocks[0]}.csv'))

In [38]:
nvidia.rename(columns={'Price':'Date'},inplace=True)

In [41]:
nvidia = nvidia.iloc[2:,:]

In [42]:
nvidia

,Date,Close,Dividends,High,Low,Open,Stock Splits,Volume
2,2015-12-28,0.8083701133728027,0.0,0.8083701133728027,0.7893439414695138,0.8005645297370835,0.0,142024000
3,2015-12-29,0.8215419054031372,0.0,0.8239811604936232,0.806662408641672,0.8088577556700381,0.0,203660000
4,2015-12-30,0.8144680857658386,0.0,0.8278840184606137,0.814224177692467,0.820810160924953,0.0,180344000
5,2015-12-31,0.8039794564247131,0.0,0.816907517611796,0.8039794564247131,0.8132486630943279,0.0,148528000
6,2016-01-04,0.7895879149436951,0.0,0.7947103350807067,0.7815383643532768,0.7876365334123907,0.0,358076000
...,...,...,...,...,...,...,...,...
2511,2025-12-18,174.13999938964844,0.0,176.14999389648438,171.82000732421875,174.52999877929688,0.0,176096000
2512,2025-12-19,180.99000549316406,0.0,181.4499969482422,176.33999633789062,176.6699981689453,0.0,324925900
2513,2025-12-22,183.69000244140625,0.0,184.16000366210938,182.35000610351562,183.9199981689453,0.0,129064400
2514,2025-12-23,189.2100067138672,0.0,189.3300018310547,182.89999389648438,182.97000122070312,0.0,174873600
2515,2025-12-24,188.61000061035156,0.0,188.91000366210938,186.58999633789062,187.94000244140625,0.0,65528500

In [44]:
for i in nvidia.columns:
    nvidia = nvidia.iloc[2:,:]
    nvidia.rename(columns={'Price':'Date'},inplace=True)
    # nvidia.set_index('Date')
    nvidia.rename(columns={f'{i}':f'NVDA-{i}'},inplace=True)

In [49]:
nvidia.iloc[-1]['Date']

'2025-12-24'

In [ ]:
nvidia.rename(columns={'Price','Date'},inplace=True)

,NVDA-Price,NVDA-Close,NVDA-Dividends,NVDA-High,NVDA-Low,NVDA-Open,NVDA-Stock Splits,NVDA-Volume
0,Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,NVDA,NVDA
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-12-28,0.8083701133728027,0.0,0.8083701133728027,0.7893439414695138,0.8005645297370835,0.0,142024000
3,2015-12-29,0.8215419054031372,0.0,0.8239811604936232,0.806662408641672,0.8088577556700381,0.0,203660000
4,2015-12-30,0.8144680857658386,0.0,0.8278840184606137,0.814224177692467,0.820810160924953,0.0,180344000
...,...,...,...,...,...,...,...,...
2511,2025-12-18,174.13999938964844,0.0,176.14999389648438,171.82000732421875,174.52999877929688,0.0,176096000
2512,2025-12-19,180.99000549316406,0.0,181.4499969482422,176.33999633789062,176.6699981689453,0.0,324925900
2513,2025-12-22,183.69000244140625,0.0,184.16000366210938,182.35000610351562,183.9199981689453,0.0,129064400
2514,2025-12-23,189.2100067138672,0.0,189.3300018310547,182.89999389648438,182.97000122070312,0.0,174873600
2515,2025-12-24,188.61000061035156,0.0,188.91000366210938,186.58999633789062,187.94000244140625,0.0,65528500

In [47]:
nvidia = nvidia.iloc[2:,:]

In [51]:
nvidia

,Date,NVDA-Close,NVDA-Dividends,NVDA-High,NVDA-Low,NVDA-Open,NVDA-Stock Splits,NVDA-Volume
16,2016-01-19,0.6666492819786072,0.0,0.6939689712790597,0.663966059783231,0.6749427403945292,0.0,457140000
17,2016-01-20,0.6703080534934998,0.0,0.6788454771482242,0.6451837150670011,0.6539650468341219,0.0,481180000
18,2016-01-21,0.6781135201454163,0.0,0.6886023223129522,0.6637218984017046,0.6776257040461604,0.0,481456000
19,2016-01-22,0.693968653678894,0.0,0.6986032552076205,0.6895779601812307,0.6910415246804519,0.0,257996000
20,2016-01-25,0.6932370662689209,0.0,0.7017744894762719,0.6917735013583536,0.6937249406245892,0.0,270728000
...,...,...,...,...,...,...,...,...
2511,2025-12-18,174.13999938964844,0.0,176.14999389648438,171.82000732421875,174.52999877929688,0.0,176096000
2512,2025-12-19,180.99000549316406,0.0,181.4499969482422,176.33999633789062,176.6699981689453,0.0,324925900
2513,2025-12-22,183.69000244140625,0.0,184.16000366210938,182.35000610351562,183.9199981689453,0.0,129064400
2514,2025-12-23,189.2100067138672,0.0,189.3300018310547,182.89999389648438,182.97000122070312,0.0,174873600
2515,2025-12-24,188.61000061035156,0.0,188.91000366210938,186.58999633789062,187.94000244140625,0.0,65528500